#!/bin/bash
#PBS -V
#FOR FUTURE PBS_O_WORK_DIR
cd /working/joliver/rjAnalysis/plotting_scripts/ThreeLepton/DEVELOPMENT

#PBS_O_WORKDIR

#cd $PBS_O_WORKDIR
#echo $PBS_O_WORKDIR
# sample location
# outputlocation
#signal region
#tree name (Nominal)
#do data 
python rootpyPlotter.py  --output $OUTPUT --region $REGION  --dataperiods $PERIOD 
#python plotSEPT.py samplesnew/ $OUTPUT $REGION Nominal 0 NOCUTFLOW
#> ABCDCUTFLOW_$REGION.log
#> TEST$REGION.log